version:  '3.8'
services:
    mysql:
        image: mysql:8.0
        restart: on-failure
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: example
            MYSQL_PASSWORD: password
            MYSQL_USER: user

    adminer:
        image: adminer
        restart: on-failure
        ports:
            - '8080:8080'
    
    nginx:
        image: nginx:1.23.3-alpine
        restart: on-failure
        volumes:
            - './apps/my-symfony-app/public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '80:80'
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - './apps/my-symfony-app/:/usr/src/app'
        restart: on-failure
        user: 501:20

    